import "./globals.css";
import Navbar from "./Components/Navbar";
import localFont from "next/font/local";
import Footer from "./Components/footer";
import LenisProvider from "./Components/LenisProvider";
import { Toaster } from "react-hot-toast";
import { CartProvider } from "./context/CartContext";
import { AuthProvider } from "./context/AuthContext";

const markpro = localFont({
  src: "../public/font/MarkPro.woff2",
  style: "normal",
  variable: "--font-markpro",
});

const markpro2 = localFont({
  src: "../public/font/MarkPro-Medium.woff2",
  style: "normal",
  variable: "--font-markpro2",
});

const markpro3 = localFont({
  src: "../public/font/MarkPro-Bold.woff2",
  style: "normal",
  variable: "--font-markpro3",
});

export const metadata = {
  title: "Green Phase",
  description: "Generated by create next app",
  icons: {
    icon: "/fav.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${markpro.variable} ${markpro2.variable} ${markpro3.variable}`}
      >
       <LenisProvider>
          <CartProvider>
            <AuthProvider>   
              {children}
            </AuthProvider>
          </CartProvider>
        </LenisProvider>

        <Toaster
          position="top-right"
          toastOptions={{
            success: {
              style: { background: "green", color: "white" },
            },
            error: {
              style: { background: "red", color: "white" },
            },
          }}
        />
      </body>
    </html>
  );
}
